# Generated by Django 4.1 on 2022-09-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField(unique=True)),
                ('nombre_categoria', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('desc', models.TextField()),
                ('foto', models.CharField(max_length=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria')),
            ],
        ),
    ]
