# Generated by Django 4.1 on 2022-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=254)),
                ('rol', models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Usuario')], default=3)),
            ],
        ),
    ]
