# Generated by Django 4.1 on 2022-09-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Cliente')], default=3),
        ),
    ]
