# Generated by Django 4.1 on 2022-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.IntegerField(null=True),
        ),
    ]
