# Generated by Django 4.1 on 2022-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0006_diamantep_marcop_materialp_pesop_sizep_tallap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('sueldo', models.IntegerField()),
                ('fecha_nac', models.DateField(verbose_name='YYYY-MM-DD')),
                ('foto', models.ImageField(default='koras_joyeria/fotos/default.png', upload_to='koras_joyeria/fotos')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
