# Generated by Django 4.1 on 2022-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0009_empleado_categoria_id_empleado_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Cliente')], default=2),
        ),
    ]
