# Generated by Django 4.0.2 on 2022-10-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0011_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
    ]
