# Generated by Django 4.0.2 on 2022-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0012_remove_producto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.SmallIntegerField(choices=[(1, 'Dorado'), (2, 'Plateado')], default=2),
            preserve_default=False,
        ),
    ]
