# Generated by Django 4.1 on 2022-11-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0016_alter_producto_options_producto_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField(unique=True)),
                ('nombre_rol', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='koras_joyeria.rol'),
            preserve_default=False,
        ),
    ]
