# Generated by Django 4.1 on 2022-11-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0017_rol_profile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='koras_joyeria.roles'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
