# Generated by Django 4.1 on 2022-11-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koras_joyeria', '0019_remove_compra_usuario_compra_user_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='nombre_rol',
        ),
        migrations.AddField(
            model_name='roles',
            name='rol',
            field=models.SmallIntegerField(choices=[(1, 'Cliente'), (2, 'Empleado'), (3, 'Administrador')], default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
