# Generated by Django 4.1 on 2022-11-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0022_role_remove_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='koras_joyeria.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='id_rol',
            field=models.IntegerField(default=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='nombre_rol',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
