# Generated by Django 4.1 on 2022-11-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0025_alter_profile_rol_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=20)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=20)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='PesoP',
        ),
        migrations.DeleteModel(
            name='TallaP',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='user',
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.pesos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talla_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.tallas'),
            preserve_default=False,
        ),
    ]
