# Generated by Django 4.1 on 2022-11-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0026_pesos_tallas_delete_pesop_delete_tallap_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pesos',
            new_name='Peso',
        ),
        migrations.RenameModel(
            old_name='Tallas',
            new_name='Talla',
        ),
    ]
