# Generated by Django 4.1 on 2022-11-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0027_rename_pesos_peso_rename_tallas_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Peso',
        ),
    ]
