# Generated by Django 4.1 on 2022-11-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0029_rename_categoria_id_talla_id_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_categoria',
        ),
    ]
