# Generated by Django 4.1 on 2022-12-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0030_remove_categoria_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/profile-default.jpg', upload_to='profiles'),
        ),
    ]
