# Generated by Django 4.1 on 2022-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0032_alter_producto_foto_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='proyecto_koras/profiles/profile-default.jpg', upload_to='proyecto_koras/profiles'),
        ),
    ]
