# Generated by Django 4.1 on 2022-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0033_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='proyecto_koras/categorias/default-categorias.png', upload_to='proyecto_koras/categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='proyecto_koras/productos/default-productos.jpg', upload_to='proyecto_koras/productos'),
        ),
    ]
