# Generated by Django 4.1 on 2022-12-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0034_categoria_foto_alter_producto_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colore',
            name='id_categoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='proyecto_koras/categorias/fontcategoria-default.jpg', upload_to='proyecto_koras/categorias'),
        ),
    ]
