# Generated by Django 4.1 on 2022-12-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0035_remove_colore_id_categoria_alter_categoria_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.colore'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.talla'),
        ),
    ]
