# Generated by Django 4.1 on 2022-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0036_alter_producto_id_categoria_alter_producto_id_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='proyecto_koras/productos/default-productos.jpg', null=True, upload_to='proyecto_koras/productos'),
        ),
    ]
