# Generated by Django 4.0.2 on 2023-01-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0037_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='proyecto_koras/productos/product-default.jpg', null=True, upload_to='proyecto_koras/productos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='proyecto_koras/profiles/profile-default.png', upload_to='proyecto_koras/profiles'),
        ),
    ]
