# Generated by Django 4.0.2 on 2023-01-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0039_rename_foto_producto_imagen_alter_categoria_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseJoya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='proyecto_koras/diseñarjoya/basejoya')),
                ('palabrasClave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnsablesPiedrasJoya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='proyecto_koras/diseñarjoya/ensamblespiedrasjoya')),
                ('palabrasClave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Joyaprediseñada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_basejoya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.basejoya')),
                ('id_ensamblespiedrasjoya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.ensablespiedrasjoya')),
            ],
        ),
    ]
