# Generated by Django 4.0.2 on 2023-01-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0040_basejoya_ensablespiedrasjoya_joyaprediseñada'),
    ]

    operations = [
        migrations.AddField(
            model_name='basejoya',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria'),
        ),
        migrations.AddField(
            model_name='ensablespiedrasjoya',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='koras_joyeria.categoria'),
        ),
    ]
