# Generated by Django 4.0.2 on 2023-01-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koras_joyeria', '0047_alter_basejoya_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diseñarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=12)),
                ('image', models.ImageField(null=True, upload_to='proyecto_koras/diseñarjoya/colores')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_color', to='koras_joyeria.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='basejoya',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_basejoya', to='koras_joyeria.diseñarcolor'),
        ),
        migrations.AddField(
            model_name='ensablespiedrasjoya',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_ensamblespiedrasjoya', to='koras_joyeria.diseñarcolor'),
        ),
    ]
